### ISSUE TITLE
Add time tracking

### ISSUE THREAD

**Issue by LeoColman** [dungeon-revealer/dungeon-revealer#1616]
Hi guys!

It's usual for me in my campaigns to track time-based events (for example, town anniversary, military exercises, or even days of travel).

It would be very nice to have this feature in dungeon-revealer.

- [ ] Edit bottom bar to include a 'calendar' view
- [ ] Add macros/commands/buttons to advance or return in time
- [ ] Add calendar entries with toggle "players can see"
- [ ] Shortcut to open the calendar view
- [ ] Include calendar duration configuration (how many days per year, months configuration, week size, week days, etc.)

I'd like to add more implementation details, but I don't know a lot about the project yet. Please feel free to add these details, it would make it easier for me (or any other contributor) to add the details.

- Files to change
- Tests to add
